project:
  type: website

website:
  title: "J.D. Dato"
  google-analytics: G-G784B87NV2
  navbar: 
    right: 
          - blog.qmd
          - text: Example Work
            href: https://jd-dato.github.io/kratomandcrime
          




format:
  html:
    theme: solar
    css: styles.css
    toc: true



