project:
  type: website

website:
  search: true
  title: "J.D. Dato"
  google-analytics: G-G784B87NV2
  navbar: 
    right:
      - blog.qmd
      - text: "Example Work"
        menu:
          - text: "Kratom and Crime"
            href: https://jd-dato.github.io/kratomandcrime/
          - text: "R Packages I've Developed"
            href: https://github.com/jd-dato/QualtricsDaysInStudy

          




format:
  html:
    theme: solar
    css: styles.css
    toc: true



